server:
  default-locale: en
  current-version: v1
  origin: http://localhost:8080 # TODO : 도메인 구입 후 수정

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.koliving.api.config.CustomNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  sql:
    init:
      mode: always
      schema-locations: sql/schema.sql
      data-locations: sql/data.sql
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.auth.validity-period: 30
  thymeleaf:
    mode: HTML
    encoding: UTF-8
  data:
    redis:
      host: localhost # TODO : redis 서버 구축 후 수정
      port: 6379

# Open API (swagger)
springdoc:
  version: 1.0.0
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger
  api-docs:
    path: /swagger/json
    groups:
      enabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.koliving.api
  cache:
    disabled: true

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}:%-3relative][%thread] %-5level %logger{35} - %msg%n"
  file:
    name: app
    path: log

jwt:
  secret: ${JWT_SECRET}
  expiration: 24 # 24 hours
  refreshExpiration: 30 # 30 days
