CREATE TABLE IF NOT EXISTS LANGUAGE (
    ID               INTEGER        AUTO_INCREMENT PRIMARY KEY,
    LOCALE           VARCHAR(5)     NOT NULL,
    MESSAGE_KEY      VARCHAR(255)   NOT NULL,
    MESSAGE_CONTENT  VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS IDX_LANGUAGE ON LANGUAGE (LOCALE, MESSAGE_KEY);
