CREATE TABLE IF NOT EXISTS USER (
    ID                  BIGINT          AUTO_INCREMENT PRIMARY KEY,
    EMAIL               VARCHAR(255)    NOT NULL,
    PASSWORD            VARCHAR(255)    NOT NULL,
    FIRST_NAME          VARCHAR(255)    NOT NULL,
    LAST_NAME           VARCHAR(105)    NOT NULL,
    BIRTH_DATE          DATE            NOT NULL,
    DESCRIPTION         VARCHAR(1000)   NOT NULL,
    GENDER              ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL,
    USER_ROLE           ENUM('USER')    NOT NULL,
    SIGNUP_STATUS       ENUM('PASSWORD_VERIFICATION_PENDING', 'PROFILE_INFORMATION_PENDING','COMPLETED') NOT NULL,
    B_ENABLED           BOOLEAN NOT NULL DEFAULT TRUE,
    B_LOCKED            BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CONFIRMATION_TOKEN (
    ID                  BIGINT         AUTO_INCREMENT PRIMARY KEY,
    TOKEN               VARCHAR(255)   NOT NULL,
    EMAIL               VARCHAR(255)   NOT NULL,
    CREATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXPIRED_DATE        TIMESTAMP,
    B_RESENDED          BOOLEAN NOT NULL DEFAULT FALSE,
    B_CONFIRMED         BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS LANGUAGE (
    ID                  BIGINT         AUTO_INCREMENT PRIMARY KEY,
    LOCALE              VARCHAR(5)     NOT NULL,
    MESSAGE_KEY         VARCHAR(255)   NOT NULL,
    MESSAGE_PATTERN     VARCHAR(255)   NOT NULL,
    CREATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY UNIQUE_LANGUAGE (LOCALE, MESSAGE_KEY)
);
