CREATE TABLE IF NOT EXISTS USER (
    ID                  BIGINT          AUTO_INCREMENT PRIMARY KEY,
    EMAIL               VARCHAR(255)    NOT NULL,
    PASSWORD            VARCHAR(255)    NOT NULL DEFAULT '',
    FIRST_NAME          VARCHAR(255)    NOT NULL DEFAULT '',
    LAST_NAME           VARCHAR(105)    NOT NULL DEFAULT '',
    BIRTH_DATE          DATE            NOT NULL DEFAULT ('1900-01-01'),
    DESCRIPTION         VARCHAR(1000)   NOT NULL DEFAULT '',
    GENDER              ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL DEFAULT 'OTHER',
    USER_ROLE           ENUM('USER', 'ADMIN')    NOT NULL,
    SIGNUP_STATUS       ENUM('PASSWORD_VERIFICATION_PENDING', 'PROFILE_INFORMATION_PENDING','COMPLETED') NOT NULL,
    B_ENABLED           BOOLEAN NOT NULL DEFAULT TRUE,
    B_LOCKED            BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CONFIRMATION_TOKEN (
    ID                  BIGINT         AUTO_INCREMENT PRIMARY KEY,
    TOKEN               VARCHAR(255)   NOT NULL,
    EMAIL               VARCHAR(255)   NOT NULL,
    CREATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXPIRED_DATE        TIMESTAMP,
    B_RESENDED          BOOLEAN NOT NULL DEFAULT FALSE,
    B_CONFIRMED         BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS LANGUAGE (
    ID                  BIGINT         AUTO_INCREMENT PRIMARY KEY,
    LOCALE              VARCHAR(5)     NOT NULL,
    MESSAGE_KEY         VARCHAR(255)   NOT NULL,
    MESSAGE_PATTERN     VARCHAR(255)   NOT NULL,
    CREATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY UNIQUE_LANGUAGE (LOCALE, MESSAGE_KEY)
);

CREATE TABLE IF NOT EXISTS TB_LOCATION (
    ID                  BIGINT         AUTO_INCREMENT PRIMARY KEY,
    UPPER_LOCATION_ID   BIGINT,
    EN_NAME             VARCHAR(50) NOT NULL,
    KR_NAME             VARCHAR(50) NULL,
    LOCATION_TYPE       VARCHAR(10) NOT NULL
);
