[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# Room
> mmd.emoticon=`house`


## Location
> mmd.emoticon=`map`


### 서울 지역을 대상으로 한다

### 구분

#### Gu

#### Dong

## Deposit
> leftSide=`true`,mmd.emoticon=`money`


### Min : 0

### Max : 500,000,000

## Monthly Rent
> leftSide=`true`,mmd.emoticon=`money`


### Min : 0

### Max : 20,000,000

## Maintenance
> mmd.emoticon=`money`


### Min : 0

### Max : 500,000,000

### options

#### Electricty

#### Water

#### Gas

#### Cleaning

### 정책

#### 관리비가 0원인 경우 option은 선택될 수 없음

#### 옵션은 여러 개 선택이 가능하다

## Date Available
> leftSide=`true`,mmd.emoticon=`time`


## Type
> mmd.emoticon=`images`


### Studio

### 1Bed Flats

### Share House

## Infomation
> leftSide=`true`,mmd.emoticon=`information`


### total bedroom

### total bathroom

### total roommates

## Furnishing
> mmd.emoticon=`bed`


### Bed

### Induction

### Air Conditioner

### Gas Stove

### Refrigerator

### Wardrobe

### Washing Machine

### Door Lock

### TV

## Images
> leftSide=`true`,mmd.emoticon=`picture`


### Min : 1

### Max : 5

## Description
> mmd.emoticon=`draft`

