name: cicd

on:
  push:
    branches:
#      - 'master'
      - 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.CONFIG_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: update permission
        run: chmod 755 ./gradlew

      - name: Build App
        run:  |
          ./gradlew copyGitSubmodule
          ./gradlew clean build -x test

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: koliving/apiserver
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: remote server connect & run script
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: ~/deploy.sh
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          privateKey: ${{ secrets.SERVER_KEY }}

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Integration Test
          fields: repo,commit,eventNAme,ref,message,author,job,took,pullRequest
          mention: here
          if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
